# Site settings
author: Ashley Archibald
title: 
header-img: img/home-bg.png
email: aarchibald20@gmail.com
copyright_name: Ashley Archibald
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ashhcashh1120

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
